// this file is automatically generated by git-version.ts script
export const versions = {
    version: '0.0.0',
    revision: '16bae95',
    branch: 'feature/36_live-example',
    repository: 'https://github.com/EvAlex/ef-db-diagrams/'
};
