// this file is automatically generated by git-version.ts script
export const versions = {
    version: '0.0.0',
    revision: 'e0a5dd9',
    branch: 'feature/40_mobile',
    repository: 'https://github.com/EvAlex/ef-db-diagrams/'
};
